---
title: "Cwiczenie 3"
author: "Hubert Kolano"
date: today
abstract-title: "Temat"
abstract: " Konstrukcja modelu w tidymodels"
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    toc-title: Spis Treści
    number-sections: true
    number-depth: 3
    embed-resources: true
    html-math-method: katex
    code-tools: true
    code-block-bg: true
    code-fold: show
    code-summary: "Show and hide code"
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    self-contained: true # a tu dobrze pan zrobił
    citation: true
    theme: 
        dark: solar
        light: flatly
    fontsize: 1.0em
    linestretch: 1.3
    fig-align: center
execute: 
  echo: true
  error: false
  warning: false
  output: true
---

```{r}
{r}
#| echo: false
library(tidymodels)
library(skimr)
library(recipes)
library(openair) 
library(GGally)
library(ggplot2)
library(ggpubr)
tidymodels_prefer()
```

# Treść zadania

```{r}
#| echo: false
2 * 2
```

The `echo: false` option disables the printing of code (only output is displayed).
